"""
Maps company names (as they appear in Job.company) to their X/Twitter handles.
Keys are lowercase for case-insensitive matching.
"""

HANDLES = {
    # Exchanges & Wallets
    "coinbase": "coinbase",
    "binance": "binance",
    "gemini": "Gemini",
    "ledger": "Ledger",
    "bitgo": "BitGo",
    "kraken": "krakenfx",
    "okx": "okx",
    "bybit": "Bybit_Official",
    "kucoin": "kucoincom",
    "bitpanda": "Bitpanda",
    "mercuryo": "mercuryo_io",

    # Infrastructure & Dev Tools
    "alchemy": "AlchemyPlatform",
    "fireblocks": "FireblocksHQ",
    "anchorage digital": "AnchorageDigital",
    "anchorage": "AnchorageDigital",
    "figment": "Figment_io",
    "chainlink labs": "chainlink",
    "chainlink": "chainlink",
    "nethermind": "NethermindEth",
    "alchemy pay": "AlchemyPay",

    # Protocols & DeFi
    "ripple": "Ripple",
    "aave": "aave",
    "aave labs": "aave",
    "1inch": "1inch",
    "ava labs": "avalancheavax",
    "avalabs": "avalancheavax",
    "uniswap": "Uniswap",
    "compound": "compoundfinance",
    "maker": "MakerDAO",
    "synthetix": "synthetix_io",
    "curve": "CurveFinance",
    "balancer": "Balancer",
    "sushiswap": "SushiSwap",
    "bancor": "Bancor",
    "zerion": "zerion",
    "kerneldao": "KernelDAO",
    "paradex": "tradeparadex",

    # L2s & Scaling
    "arbitrum": "arbitrum",
    "optimism": "optimismFND",
    "polygon": "0xPolygon",
    "polygon labs": "0xPolygon",
    "starkware": "StarkWareLtd",
    "starknet": "Starknet",
    "base": "base",
    "scroll": "Scroll_ZKP",
    "linea": "LineaBuild",
    "immutable": "Immutable",
    "immutable x": "Immutable",

    # NFT & Gaming
    "magic eden": "MagicEden",
    "opensea": "opensea",
    "blur": "blur_io",
    "axie infinity": "AxieInfinity",

    # Research & Security
    "messari": "MessariCrypto",
    "nansen": "nansen_ai",
    "certik": "CertiK",
    "consensys": "ConsenSys",
    "paradigm": "paradigm",
    "a16z crypto": "a16zcrypto",
    "delphi digital": "Delphi_Digital",

    # Ecosystem
    "solana foundation": "solana",
    "solana": "solana",
    "near": "NEARProtocol",
    "near protocol": "NEARProtocol",
    "cosmos": "cosmos",
    "aptos": "Aptos",
    "sui": "SuiNetwork",
    "wintermute": "wintermute_t",
    "cere": "CereNetwork",
    "headstart": "HeadstartApp",

    # Additional companies appearing in filtered results
    "bitmex": "BitMEX",
    "crypto.com": "cryptocom",
    "galaxy digital services": "galaxyhq",
    "galaxy digital": "galaxyhq",
    "mantle": "0xMantle",
    "logos": "logosnetwork",
    "sei development foundation": "SeiNetwork",
    "sei": "SeiNetwork",
    "squads": "SquadsProtocol",
    "sherlock": "sherlockdefi",
    "seedify.fund": "SeedifyFund",
    "seedify": "SeedifyFund",
    "figure": "FigureTech",
    "fedi, inc.": "fedibtc",
    "fedi": "fedibtc",
    "propy": "PropyInc",
    "bifrost foundation": "BifrostNetwork",
    "bifrost": "BifrostNetwork",
    "alphapoint": "alphapoint",
    "kernel dao": "KernelDAO",
    "morph network": "Morphl2",
    "morph": "Morphl2",
    "sentient": "sentient_agi",
    "douro labs": "DourolabsHQ",
    "douro": "DourolabsHQ",
    "opensea": "opensea",
    "green dots": "greenDOTs_io",
    "bitso": "Bitso",
    "inmobi": "InMobi",
    "ergonia": "ergonia_io",
}
